models:
  Encoder:
    name: 'MinkUNet34Encoder'
    in_feat_size: 1
    out_classes: 19
    out_feature: 96
    resume_path: 'pretrained_models/synlidar/semantickitti/checkpoint/pretrained_model.ckpt'
    # resume_path: 'experiments/defense/synlidar/semantickitti/2024_06_02_16:23_SOURCE-DEFENSE-LIDAR2KITTI-KL-CHAMFER/checkpoints/epoch=99-step=24799.ckpt'
  Decoder:
    name: 'ConvDecoder'
    # in_feat_size: 19
    in_feat_size: 96
    out_classes: 3
    resume_path: 'experiments/defense/synlidar/semantickitti/2024_06_04_03:27_SOURCE-DEFENSE-LIDAR2KITTI-ChamferUpdate/checkpoints/epoch=49-step=24799.ckpt'
log:
  name: defense.log
  save_dir: log/defense/eval/

defense:
  sampling_rate: 0.25
  # noise: 0.25
  noise: 0.1
  split_dir: 'test/select_split'
  split_name: 'split.pth'

result:
  save_dir: 'recovery'
  save_name: 'recovery_points.png'

dataset:
  version: 'full'
  name: 'SynLiDAR'
  dataset_path: 'data/SynLiDAR/sequences'
  mapping_path: '_resources/synlidar_semantickitti.yaml'
  target: 'SemanticKITTI'
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: true

pipeline:
  epochs: 10
  steps: null
  gpus: [0]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/defense/synlidar/semantickitti'
  validate_target: true

  dataloader:
    batch_size: 1
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 2

  wandb:
    run_name: 'SOURCE-DEFENSE-LIDAR2KITTI'
    project_name: 'ATTACK_COSMIX_SDIM'
    entity_name: 'sdim2chenjj'
    offline: true
