model:
  resume_path: 'pretrained_model/synlidar/semantickitti/checkpoint/pretrained_model.ckpt'
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 19

dataset:
  version: 'full'
  name: 'SynLiDAR'
  dataset_path: 'data/SynLiDAR/sequences'
  mapping_path: '_resources/synlidar_semantickitti.yaml'
  target: 'SemanticKITTI'
  voxel_size: 0.05
  num_pts: 80000
  ignore_label: -1
  augment_data: true

eval:
  resume_path: 'experiments/attacked_cosmix/baseline/synlidar/semantickitti/2024_05_15_15:56_Cosmix_Attack_100%_UKitti/'
  eval_source: false
  eval_target: true
  is_student: true
  save_predictions: false


pipeline:
  epochs: 100
  steps: null
  gpus: [0]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/pretrained/synlidar/semantickitti'
  validate_target: true

  dataloader:
    batch_size: 4
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 2


