model:
  # resume_path: 'experiments/adv_pretrained/synlidar/semanticposs/checkpoints/epoch=19-step=12399.ckpt'
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 13

dataset:
  version: 'full'
  name: 'SynLiDAR'
  dataset_path: 'data/SynLiDAR/sequences'
  mapping_path: '_resources/synlidar_semanticposs.yaml'
  target: 'SemanticPOSS'
  voxel_size: 0.05
  num_pts: 50000
  ignore_label: -1
  augment_data: true

attacked:
  prob: 1.
  adv_path: 'experiments/SAVEDIR/attackedLidar_Poss100'

pipeline:
  epochs: 80
  steps: null
  gpus: [0,1]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/adv_pretrained/synlidar/semanticposs'
  validate_target: true

  dataloader:
    batch_size: 4
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.01

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0


  wandb:
    run_name: 'LIDAR2POSS_WARMUP_ATTACKED_SOURCE_100'
    project_name: 'ATTACK_COSMIX'
    entity_name: 'sdim2chenjj'
    offline: true
